// Date: 2019/9/25 19:24:06
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.lh_lshen.mcbbs.huajiage.client.render.model;

import com.lh_lshen.mcbbs.huajiage.entity.EntityRoadRoller;
import com.lh_lshen.mcbbs.huajiage.item.ItemLoader;

import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.block.model.ItemCameraTransforms.TransformType;
import net.minecraft.entity.Entity;
import net.minecraft.item.ItemStack;

public class ModelRoadRoller extends ModelBase
{
  //fields
  
  @Override
public void render(Entity entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw,
		float headPitch, float scale) {
	  if(entityIn instanceof EntityRoadRoller) {
		  EntityRoadRoller road = (EntityRoadRoller) entityIn;
		  if(road.getType().equals(EntityRoadRoller.enumTYPE.ROAD_ROLLER.getName())) {
		  ItemStack item=new ItemStack(ItemLoader.roadRoller);
		  Minecraft.getMinecraft().getRenderItem().renderItem(item, TransformType.GROUND);
		  }else if(road.getType().equals(EntityRoadRoller.enumTYPE.CAR.getName())){
		  ItemStack item=new ItemStack(ItemLoader.blackCar);
		  Minecraft.getMinecraft().getRenderItem().renderItem(item, TransformType.GROUND);
		  }
	  }
    setRotationAngles( limbSwing, limbSwingAmount, ageInTicks, headPitch,netHeadYaw, scale);
	super.render(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scale);
}
 
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
