// Date: 2019/4/28 15:11:46
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.lh_lshen.mcbbs.huajiage.client.model;

import javax.annotation.Nonnull;

import com.lh_lshen.mcbbs.huajiage.item.BlancedHelmet;
import com.lh_lshen.mcbbs.huajiage.item.ItemLoader;
import com.lh_lshen.mcbbs.huajiage.item.ItemLordCore;

import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.block.model.ItemCameraTransforms.TransformType;
import net.minecraft.entity.Entity;
import net.minecraft.entity.item.EntityArmorStand;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.ItemStack;

public class ModelBlanceHelmet extends ModelArmor
{
	

  //fields
    ModelRenderer p1;
    ModelRenderer p2;
    ModelRenderer p3;
    ModelRenderer p4;
    ModelRenderer p5;
    ModelRenderer p6;
    ModelRenderer p7;
    ModelRenderer p8;
    ModelRenderer p9;
    ModelRenderer Base1;
    ModelRenderer Base2;
    ModelRenderer Base3;
    ModelRenderer Base4;
  
    public ModelBlanceHelmet(EntityEquipmentSlot slot) {
		super(slot);
    textureWidth = 64;
    textureHeight = 32;
    
    p1 = new ModelRenderer(this, 14, 28);
    p1.addBox(4.466667F, -6F, 0F, 2, 2, 2);
    p1.setRotationPoint(0F, 0F, 0F);
    p1.setTextureSize(64, 32);
    p1.mirror = true;
    setRotation(p1, 0F, 0F, 0F);
    p2 = new ModelRenderer(this, 0, 0);
    p2.addBox(-6F, -6.466667F, -6F, 1, 5, 6);
    p2.setRotationPoint(0F, 0F, 0F);
    p2.setTextureSize(64, 32);
    p2.mirror = true;
    setRotation(p2, 0F, 0F, 0F);
    p3 = new ModelRenderer(this, 0, 21);
    p3.addBox(-5F, -7F, -6F, 10, 7, 1);
    p3.setRotationPoint(0F, 0F, 0F);
    p3.setTextureSize(64, 32);
    p3.mirror = true;
    setRotation(p3, 0F, 0F, 0F);
    p4 = new ModelRenderer(this, 0, 28);
    p4.addBox(-6.466667F, -6F, 0F, 2, 2, 2);
    p4.setRotationPoint(0F, 0F, 0F);
    p4.setTextureSize(64, 32);
    p4.mirror = true;
    setRotation(p4, 0F, 0F, 0F);
    p5 = new ModelRenderer(this, 0, 0);
    p5.addBox(5F, -6.466667F, -6F, 1, 5, 6);
    p5.setRotationPoint(0F, 0F, 0F);
    p5.setTextureSize(64, 32);
    p5.mirror = true;
    setRotation(p5, 0F, 0F, 0F);
    p6 = new ModelRenderer(this, 0, 0);
    p6.addBox(-4F, -4F, -7F, 8, 1, 1);
    p6.setRotationPoint(0F, 0F, 0F);
    p6.setTextureSize(64, 32);
    p6.mirror = true;
    setRotation(p6, 0F, 0F, 0F);
    p7 = new ModelRenderer(this, 0, 0);
    p7.addBox(-4F, -6F, -7F, 8, 1, 1);
    p7.setRotationPoint(0F, 0F, 0F);
    p7.setTextureSize(64, 32);
    p7.mirror = true;
    setRotation(p7, 0F, 0F, 0F);
    p8 = new ModelRenderer(this, 0, 0);
    p8.addBox(-4F, -5F, -7F, 1, 1, 1);
    p8.setRotationPoint(0F, 0F, 0F);
    p8.setTextureSize(64, 32);
    p8.mirror = true;
    setRotation(p8, 0F, 0F, 0F);
    p9 = new ModelRenderer(this, 0, 0);
    p9.addBox(3F, -5F, -7F, 1, 1, 1);
    p9.setRotationPoint(0F, 0F, 0F);
    p9.setTextureSize(64, 32);
    p9.mirror = true;
    setRotation(p9, 0F, 0F, 0F);
    Base1 = new ModelRenderer(this, 0, 0);
    Base1.addBox(-5F, -9F, -5F, 10, 4, 10);
    Base1.setRotationPoint(0F, 0F, 0F);
    Base1.setTextureSize(64, 32);
    Base1.mirror = true;
    setRotation(Base1, 0F, 0F, 0F);
    Base2 = new ModelRenderer(this, 12, 5);
    Base2.addBox(-4F, -5F, 4F, 8, 3, 1);
    Base2.setRotationPoint(0F, 0F, 0F);
    Base2.setTextureSize(64, 32);
    Base2.mirror = true;
    setRotation(Base2, 0F, 0F, 0F);
    Base3 = new ModelRenderer(this, 0, 0);
    Base3.addBox(-5F, -5F, 0F, 1, 5, 5);
    Base3.setRotationPoint(0F, 0F, 0F);
    Base3.setTextureSize(64, 32);
    Base3.mirror = true;
    setRotation(Base3, 0F, 0F, 0F);
    Base4 = new ModelRenderer(this, 0, 0);
    Base4.addBox(4F, -5F, 0F, 1, 5, 5);
    Base4.setRotationPoint(0F, 0F, 0F);
    Base4.setTextureSize(64, 32);
    Base4.mirror = true;
    setRotation(Base4, 0F, 0F, 0F);
      this.Base1.addChild(Base2);
      this.Base1.addChild(Base3);
      this.Base1.addChild(Base4);
      this.Base1.addChild(p1);
      this.Base1.addChild(p2);
      this.Base1.addChild(p3);
      this.Base1.addChild(p4);
      this.Base1.addChild(p5);
      this.Base1.addChild(p6);
      this.Base1.addChild(p7);
      this.Base1.addChild(p8);
      this.Base1.addChild(p9);
  }
  
    @Override
	public void render(@Nonnull Entity entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scale) {
		
		Base1.showModel = slot == EntityEquipmentSlot.HEAD;

		
		bipedHeadwear.showModel = false;

		bipedHead = Base1;
		super.render(entity, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scale);
		if(entity instanceof EntityPlayer) {
			ItemStack stack=((EntityPlayer)entity).getItemStackFromSlot(EntityEquipmentSlot.HEAD);
			if(stack.getItem() instanceof BlancedHelmet) {
				if(stack.getTagCompound().hasKey("active")) {
					Minecraft.getMinecraft().getRenderItem().renderItem(new ItemStack(ItemLoader.lordCore), TransformType.HEAD);
				}
			}
		}
	}
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
 

}

